version: '3.1'

services:

  scswdb:
    image: debezium/postgres:12
    container_name: scswdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tux#997799
      - POSTGRES_DB=scswdb
    ports:
      - 5432:5432
    volumes:
      - scswdb:/var/lib/postgresql/data
      - ./scs-writer/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - beacukaiNet

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./scs-writer/src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - beacukaiNet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - beacukaiNet

  scsrdb:
    image: postgres:12 
    container_name: scsrdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tux#997799
      - POSTGRES_DB=scsrdb
    ports:
      - 5431:5432
    volumes:
      - scsrdb:/var/lib/postgresql/data
    networks:
      - beacukaiNet

  zookeeper:
    image: debezium/zookeeper:1.1 
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - beacukaiNet

  kafka:
    image: debezium/kafka:1.1 
    hostname: kafka 
    container_name: kafka 
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - beacukaiNet

  connect:
    image: debezium/connect:1.1
    hostname: connect
    container_name: connect
    depends_on:
      - kafka
      - scswdb
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=scs_group
      - CONFIG_STORAGE_TOPIC=scs_storage_topic
      - OFFSET_STORAGE_TOPIC=scs_offset_topic 
    networks:
      - beacukaiNet

volumes:
  scswdb:
  scsrdb:

networks:
  beacukaiNet:
    driver: bridge
