CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS header(
    id_header varchar(255) NOT NULL DEFAULT uuid_generate_v4(),
    asal_data varchar(3) NOT NULL,
    asuransi decimal(15,2) DEFAULT 0.00,
    biaya_pengurang decimal(15,2) DEFAULT 0.00,
    biaya_tambahan decimal(15,2) DEFAULT 0.00,
    bruto decimal(15,2) DEFAULT 0.00,
    cif varchar(100),
    dasar_pengenaan_pajak varchar(255),
    disclaimer varchar(500),
    email varchar(255),
    flag_curah boolean default false,
    flag_migas boolean default false,
    flag_pph boolean default false,
    flag_sda boolean default false,
    flag_vd boolean default false,
    fob varchar(255),
    freight double precision,
    harga_penyerahan decimal(15,2) default 0.00,
    harga_perolehan decimal(15,2) default 0.00,
    id_pelmuat_akhir varchar(255),
    id_pengguna varchar(255),
    id_perusahaan varchar(255) NOT NULL,
    id_ppjk varchar(255),
    jabatan_ttd varchar(255),
    jatuh_tempo_billing timestamp,
    jumlah_bruto decimal(15,2) default 0.00,
    jumlah_cif decimal(15,2) default 0.00,
    jumlah_fob decimal(15,2) default 0.00,
    jumlah_harga_penyerahan decimal(15,2) default 0.00,
    jumlah_kontainer int,
    jumlah_netto int,
    jumlah_nilai_barang decimal(15,2) default 0.00,
    jumlah_nilai_vd decimal(15,2) default 0.00,
    jumlah_tanda_pengaman int,
    jumlah_volume double precision,
    kode_asal_barang_ftz varchar(255),
    kode_asuransi varchar(100),
    kode_bank varchar(100),
    kode_billing varchar(100),
    kode_cara_angkut_plb varchar(10),
    kode_cara_bayar varchar(10),
    kode_cara_dagang varchar(10),
    kode_daerah_asal varchar(100),
    kode_dokumen varchar(10),
    kode_faktur varchar(100),
    kode_gudang_asal varchar(50),
    kode_gudang_tujuan varchar(50),
    kode_incoterm varchar(100),
    kode_jenis_ekspor varchar(50),
    kode_jenis_impor varchar(50),
    kode_jenis_kirim varchar(50),
    kode_jenis_nilai varchar(50),
    kode_jenis_pengiriman varchar(50),
    kode_jenis_plb varchar(50),
    kode_jenis_prosedur varchar(50),
    kode_jenis_tanda_pengaman varchar(50),
    kode_jenis_tpb varchar(50),
    kode_kantor varchar(50),
    kode_kantor_bongkar varchar(50),
    kode_kantor_ekspor varchar(50),
    kode_kantor_muat varchar(50),
    kode_kantor_periksa varchar(50),
    kode_kantor_tujuan varchar(50),
    kode_kategori_barang_ftz varchar(50),
    kode_kategori_ekspor varchar(50),
    kode_kategori_keluar_ftz varchar(50),
    kode_kategori_masuk_ftz varchar(50),
    kode_kena_pajak varchar(50),
    kode_lokasi varchar(50),
    kode_lokasi_bayar varchar(50),
    kode_negara_tujuan varchar(50),
    kode_pel_bongkar varchar(50),
    kode_pel_ekspor varchar(50),
    kode_pel_muat varchar(50),
    kode_pel_transit varchar(50),
    kode_pel_tujuan varchar(50),
    kode_pembayar varchar(50),
    kode_tps varchar(50),
    kode_tujuan_pemasukan varchar(50),
    kode_tujuan_pengiriman varchar(50),
    kode_tujuan_tpb varchar(50),
    kode_tutup_pu varchar(50),
    kode_valuta varchar(10),
    kode_ttd varchar(50),
    lokasi_asal varchar(100),
    lokasi_tujuan varchar(100),
    nama_cara_bayar varchar(100),
    nama_incoterm varchar(100),
    nama_jenis_impor varchar(100),
    nama_jenis_nilai varchar(100),
    nama_jenis_prosedur varchar(100),
    nama_jenis_tpb varchar(100),
    nama_kantor_bongkar varchar(255),
    nama_kantor_muat varchar(255),
    nama_kantor_pendek varchar(100),
    nama_kantor_tujuan varchar(255),
    nama_pelabuhan_bongkar varchar(255),
    nama_pelabuhan_muat varchar(255),
    nama_pelabuhan_tujuan varchar(255),
    nama_perusahaan varchar(255) not null,
    nama_ppjk varchar(255),
    nama_proses varchar(255),
    nama_transaksi_lainnya_ftz varchar(255),
    nama_ttd varchar(255),
    nama_valuta varchar(50),
    ndpbm varchar(100),
    netto varchar(100),
    nik varchar(100),
    nilai_barang decimal(15,2) default 0.00,
    nilai_incoterm decimal(15,2) default 0.00,
    nilai_jasa decimal(15,2) default 0.00,
    nilai_kurs decimal(15,2) default 0.00,
    nilai_maklon decimal(15,2) default 0.00,
    nip_rekam varchar(100),
    nomor_aju varchar(100) not null unique,
    nomor_bc11 varchar(100),
    nomor_bukti_bayar varchar(100),
    nomor_daftar varchar(100),
    npppjk varchar(100),
    npwp_billing varchar(100),
    npwp_pemusatan varchar(100),
    pos_bc11 varchar(100),
    role_entitas varchar(100) NOT NULL,
    seri int,
    subpos_bc11 varchar(100),
    tanggal_aju date,
    tanggal_Bc11 date,
    tanggal_berangkat date,
    tanggal_billing date,
    tanggal_bukti_bayar date,
    tanggal_daftar date,
    tanggal_ekspor date,
    tanggal_ijin_penerima date,
    tanggal_ijin_pengusaha date,
    tanggal_masuk date,
    tanggal_muat date,
    tanggal_npppjk date,
    tanggal_periksa date,
    tanggal_stuffing date,
    tgl_akhir_berlaku date,
    tgl_awal_berlaku date,
    total_dana_sawit decimal(15,2) default 0.00,
    tt_barang varchar(100),
    uang_muka decimal(15,2) default 0.00,
    url_dokumen varchar(500),
    user_portal varchar(25),
    vd varchar(100),
    versi_modul varchar(25),
    volume double precision
);

ALTER TABLE header ADD PRIMARY KEY(id_header);

CREATE TABLE IF NOT EXISTS domain_events(
    event_id varchar(255) NOT NULL DEFAULT uuid_generate_v4(),
    event_type varchar(255) NOT NULL,
    version bigint default 0,
    event_handler varchar(500) NOT NULL,
    event_reference_id varchar(255),
    data text NOT NULL,
    timestamp timestamp NOT NULL DEFAULT now(),
    created_by varchar(25)
);

ALTER TABLE domain_events ADD PRIMARY KEY(event_id);